import Link from 'next/link'
import Image from 'next/image'
import { ArrowUpRight, Clock3, RotateCcw, Truck } from 'lucide-react'
import { readActiveProducts } from '@/lib/supabase-server'
import { mapSupabaseProduct } from '@/lib/products'
import { ProductCard } from '@/components/product-card'
import { HomeCopy } from '@/components/home-copy'
export const dynamic = 'force-dynamic'
export default async function Home() { const products=(await readActiveProducts()).map(mapSupabaseProduct); const firstProductHref=products[0]?`/product/${encodeURIComponent(products[0].slug)}`:'/shop'; return <main><section className="relative min-h-[620px] overflow-hidden bg-[#f7f4f0]"><Image src="/diva-heels-hero.png" alt="Diva Heels — елегантни обувки с висок ток" fill priority className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-white/90 via-white/35 to-transparent"/><div className="relative mx-auto flex min-h-[620px] max-w-7xl items-center px-5 lg:px-10"><HomeCopy firstProductHref={firstProductHref}/></div></section><section className="border-b border-[#e8e5e1]"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 md:grid-cols-3 lg:px-10">{[[Truck,'freeShipping','До всяка точка в България.'],[Clock3,'delivery','Бърза обработка и доставка.'],[RotateCcw,'returns','Ясна и лесна процедура за връщане.']].map(([Icon,key,desc]:any)=><div className="flex items-center gap-4" key={key}><Icon className="h-5 w-5 stroke-[1.2] text-[#b79a66]"/><div><h3 className="text-sm">{key==='freeShipping'?'Безплатна доставка':key==='delivery'?'До 2 работни дни':'Връщане до 14 дни'}</h3><p className="mt-1 text-xs text-[#666]">{desc}</p></div></div>)}</div></section><section className="mx-auto max-w-7xl px-5 py-24 lg:px-10"><div className="mb-10 flex items-end justify-between"><div><p className="mb-3 text-[10px] uppercase tracking-[.25em] text-[#b79a66]">Diva Heels</p><h2 className="font-editorial text-5xl">Нашият подпис</h2></div><Link href="/shop" className="hidden items-center gap-2 text-xs uppercase tracking-[.15em] md:flex">Всички модели <ArrowUpRight className="h-4 w-4"/></Link></div><div className="grid gap-8 md:grid-cols-3">{products.slice(0,3).map(product=><ProductCard key={product.id} product={product}/>)}</div></section><section className="mx-5 bg-[#111] px-6 py-20 text-center text-white lg:mx-10"><p className="text-[10px] uppercase tracking-[.25em] text-[#b79a66]">Diva Heels</p><h2 className="mx-auto mt-5 max-w-2xl font-editorial text-5xl leading-none md:text-7xl">Красотата започва с увереност.</h2><Link href="/about" className="mt-8 inline-block border border-white/40 px-7 py-4 text-xs uppercase tracking-[.15em]">Научи повече</Link></section></main> }
