import 'server-only'
const supabaseUrl=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;const serviceRoleKey=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY
function getConfig(){if(!supabaseUrl||!serviceRoleKey)throw new Error('Supabase server configuration is missing.');return{supabaseUrl,serviceRoleKey}}
function headers(){const{serviceRoleKey}=getConfig();return{apikey:serviceRoleKey,Authorization:`Bearer ${serviceRoleKey}`,'Content-Type':'application/json'}}
export async function insertOrder(order:Record<string,unknown>,items:Record<string,unknown>[]){const{supabaseUrl}=getConfig();const response=await fetch(`${supabaseUrl}/rest/v1/orders`,{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(order),cache:'no-store'});if(!response.ok)throw new Error(`Unable to create order (${response.status}).`);const[created]=await response.json();const itemResponse=await fetch(`${supabaseUrl}/rest/v1/order_items`,{method:'POST',headers:headers(),body:JSON.stringify(items.map(i=>({...i,order_id:created.id}))),cache:'no-store'});if(!itemResponse.ok)throw new Error(`Unable to create order items (${itemResponse.status}).`);return created}
export async function updateOrder(id:string,values:Record<string,unknown>){const{supabaseUrl}=getConfig();const r=await fetch(`${supabaseUrl}/rest/v1/orders?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=minimal'},body:JSON.stringify(values),cache:'no-store'});if(!r.ok)throw new Error(`Unable to update order (${r.status}).`)}
export async function readActiveProducts(){const{supabaseUrl}=getConfig();const r=await fetch(`${supabaseUrl}/rest/v1/products?active=eq.true&order=created_at.desc`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error('Unable to read products.');return r.json()}
export async function readActiveProductsBySlugs(slugs:string[]){const{supabaseUrl}=getConfig();const encoded=slugs.map(s=>`"${s.replaceAll('"','')}"`).join(',');const r=await fetch(`${supabaseUrl}/rest/v1/products?active=eq.true&slug=in.(${encodeURIComponent(encoded)})`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error('Unable to validate products.');return r.json()}
export async function readOrder(id:string){const{supabaseUrl}=getConfig();const r=await fetch(`${supabaseUrl}/rest/v1/orders?id=eq.${encodeURIComponent(id)}&select=*,order_items(*)`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error('Unable to read order.');const rows=await r.json();return rows[0]??null}
